### PR TITLE
Suppress almost all warnings

### PR DESCRIPTION
**Pull request by okkez**
See also https://github.com/fluent/fluentd/issues/848

### CODE REVIEW

**Comment by okkez** [comment]
Remains following warning:

```
lib/cool.io/loop.rb:41: warning: method redefined; discarding old initialize
```

This is caused by definitions of `Cool::IO::Loop#initialize` at followings

* https://github.com/tarcieri/cool.io/blob/master/lib/cool.io/loop.rb#L41
* https://github.com/tarcieri/cool.io/blob/master/ext/cool.io/loop.c#L47

I think we can remove C version of `Cool::IO::Loop#initialize`.

**Comment by okkez** [comment]
@repeatedly How about this PR?

See also https://github.com/fluent/fluentd/issues/848

**Comment by repeatedly** [comment]
LGTM

**Comment by tagomoris** [comment]
@repeatedly  Could you release new version including this change?

**Comment by repeatedly** [comment]
Already released several hours ago.

**Comment by tagomoris** [comment]
Thank you!

**Pull request merged**
