### PR TITLE
Support Ruby 3.0 on fat gem

### LINKED ISSUE #74: cool.io v1.7.1 fat gem doesn't include Ruby 3.0 binaries
On Windows, users still couldn't use cool.io v1.7.1 fat gem.
`rubygems` complains as follows:

```
cool.io-1.7.1-x64-mingw32 requires ruby version < 2.8.dev, >= 2.4, which is
incompatible with the current version, ruby 3.0.0p0
rake aborted!
```

### PR DESCRIPTION
**Pull request by cosmo0920**
Fixes #74.

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

### CODE REVIEW

**Comment by cosmo0920** [comment]
@repeatedly, @ashie Could you kindly take a look?

**Comment by repeatedly** [comment]
Thanks!

**Comment by repeatedly** [comment]
I hit following errors:

```
rake aborted!
Gem::InvalidSpecificationException: ["lib/3.0/cool.io_ext.so", "lib/3.0/iobuffer_ext.so"] are not files
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.5.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `eval'
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => gem => pkg/cool.io-1.7.2-x86-mingw32.gem
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker run -v ...]
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.6.0/gems/rake-compiler-dock-1.1.0/lib/rake_compiler_dock/starter.rb:96:in `block in exec'
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.6.0/gems/rake-compiler-dock-1.1.0/lib/rake_compiler_dock/starter.rb:46:in `each'
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.6.0/gems/rake-compiler-dock-1.1.0/lib/rake_compiler_dock/starter.rb:46:in `exec'
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.6.0/gems/rake-compiler-dock-1.1.0/lib/rake_compiler_dock/starter.rb:14:in `sh'
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.6.0/gems/rake-compiler-dock-1.1.0/lib/rake_compiler_dock.rb:46:in `sh'
/Users/repeatedly/dev/cool.io/Rakefile:50:in `block (2 levels) in <top (required)>'
/Users/repeatedly/dev/cool.io/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/repeatedly/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/repeatedly/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
Tasks: TOP => build:windows
(See full trace by running task with --trace)
```

Could you tell me your build setting?

**Comment by cosmo0920** [comment]
> Could you tell me your build setting or release new gem via your environment?

Sure, I'll do.

**Comment by cosmo0920** [comment]
rake-compiler-dock 1.1.0 starts to support Ruby 3.0 cross compilation.
We need to update rake-compiler-dock v1.1.x first.
Then, I got succeeded to build Ruby 3.0 extension binary bundled gems.

**Comment by cosmo0920** [comment]
Or, Should I release a new version and push them into rubygems?
I can do it, too.
If you add me into cool.io owner in rubygems.org, please use emailme address into owner email.
My rubygems account is:
https://rubygems.org/profiles/cosmo0920

**Comment by repeatedly** [comment]
I use latest rake-compiler-deck but I got above errors. Maybe, my ruby environemnt is something wrong.

BTW, I added you to cool.io owner. Check the email.

**Comment by cosmo0920** [comment]
Thanks. I'd accept cool.io owner inviting.

**Pull request merged**
